# Manipulando Variáveis e Constantes 

- Variáveis são utilizadas para armazenar os dados 

- Qualquer dado que possa ser alterado no decorrer do tempo é uma variável.

- Se o dado não tem possibilidade de variar no decorrer do tempo é uma constante.

Ex: Calacular a área de um triângulo. A formula Base * Altura / 2
Base e Altura são os dados que irão variar ao decorrer do "tempo de execução", já o número 2 da fórmula é uma constante pois sempre será o mesmo valor. 

Tipos de Variáveis 

- Inteiros: Valores positivos ou negativos, que não tem parte fracionária.

- Float(real): Valores positivos ou negativos, que podem ter uma parte fracionária (tambem podem ser inteiros).

- Caracteres(char ou string): Qualquer elemento presente no teclado.

- Lógico(boleano): Verdadeiro(1) ou falso(0)  


## Variáveis Inteiras

In [2]:
number = -9
number2 = 18
number3 = 36

## Variáveis Float

In [3]:
pi = 3.14
number_euler = 2.71
number - 4.35

-13.35

## String e Chars

In [1]:
letter = 'l'
word = 'language programming'
word2 = 'Python' 

## Input


In [10]:
age = int(input('Enter with your age: '))
print(f'Your age is... {age}')

Your age is... 5


In [14]:
ph = float(input('What was the soil PH during the last measurement?'))
print('The measured PH was:',ph)

The measured pH was: 5.0


In [11]:
name = str(input('What is your name?'))
print('Your name is', name)

Your name is lucas


# String Manipulate

In [18]:
str1 = 'whatever'
str1

'whatever'

In [19]:
upper_str = str1.upper()
print(upper_str)

WHATEVER


In [20]:
lower_str = upper_str.lower()
lower_str

'whatever'

In [21]:
capitalize_str = str1.capitalize()
print(capitalize_str)

Whatever


In [25]:
mean_word = str1[0:3]
print(mean_word)

wha


In [27]:
last_letter = str1[3:]
last_letter

'tever'

In [28]:
str2 = str1.replace('wha', 'AAAAAAA')
str2

'AAAAAAAtever'

In [33]:
str3 = str1.replace('r', 'O')
str3

'whateveO'

In [37]:
str3.find('o')

-1

In [39]:
str3.find('O')

7

In [36]:
str3.find('e')

4

In [42]:
str4 = 'Hellooooooo'
len_str = len(str4)
len_str

11

In [44]:
number1 = 9
number2 = 10
print(f'{number1} / {number2} = {number1 / number2}') 

9 / 10 = 0.9


# Math Operations

In [45]:
value = 5
value2 = 3
print(value, value2)

5 3


In [46]:
addition = value + value2
addition

8

In [48]:
subtraction = value - value2 
subtraction

2

In [49]:
multiplication = value * value2
multiplication

15

In [51]:
divison = value / value2
divison

1.6666666666666667

In [53]:
remainder_division = value % value2
remainder_division

2

In [55]:
exponentiation = value**3
exponentiation

125

In [57]:
from math import sqrt

sqrt(81)

9.0

## Rounding

In [59]:
case_disease = 134
numbers_inhabitants = 34432

cases_per_inhabitant = case_disease / numbers_inhabitants
cases_per_inhabitant

0.003891728624535316

In [60]:
round(cases_per_inhabitant, 6)

0.003892

In [62]:
round(cases_per_inhabitant, 3)

0.004

# Logical and Relational Operators

## Logical Operators

In [1]:
x = True
y = False

In [2]:
x and y
x & y

False

In [3]:
print(f"'X' and 'Y' is equals: {x and y}")

'X' and 'Y' is equals: False


In [4]:
x or y
x | y

True

In [5]:
print(f"'X' or 'Y' is equals: {x or y}")

'X' or 'Y' is equals: True


In [6]:
not x

False

In [7]:
not y

True

## Relational Operators

In [8]:
10 > 5

True

In [9]:
9 < 10

True

In [10]:
9 >= 10

False

In [11]:
9 <= 10

True

In [12]:
9 == 10

False

In [13]:
9 != 10


True

# Conditional Operator

In [14]:
9 < 10

True

In [21]:
if 9 > 6:
    print('9 is greater than 6')
# print('opaaaa')

9 is greater than 6


In [27]:
if 5 > 6:
    print(' 5 is greater')
else:
    print('isnt greater')

isnt greater


In [29]:
n = 9
if n == 4:
    print('n isnt equal 4') 
else:
    if n == 9:
        print('n is equal 9')
    else: 
        print('n isnt equal to 4 and 9')

n is equal 9


In [35]:
x = 2 
y = 4

if (x > 1) and (y % 2  == 0):
    print('X greater than 1 and y is even')
else:
    print('something is wrong ')

X greater than 1 and y is even


In [37]:
x = 1 
y = 3

if (x > 1) or (y % 2  == 0):
    print('X greater than 1 and y is even')
else:
    print('something is wrong ')

something is wrong 


# Loop For

In [2]:
for i in range(1,6):
    print(i)

1
2
3
4
5


In [9]:
for  i in range(5, 0 , -1):
    print(i)

5
4
3
2
1


In [19]:
sum = 0
for i in range(1,6):
    sum += i
    print(sum)
print(sum)

1
3
6
10
15
15


In [18]:
word = 'ice cream'
for i in word:
    print(i)
    if i == 'r':
        print('Found the word r ')

i
c
e
 
c
r
Found the word r 
e
a
m


In [21]:
for i in range(5):
    print(i)
    print('-')
    for ii in range(3):
        print(ii)
    print()

0
-
0
1
2

1
-
0
1
2

2
-
0
1
2

3
-
0
1
2

4
-
0
1
2



# Loop While

In [25]:
number = 1
while number < 6:
    print(number)
    number += 1

1
2
3
4
5


In [26]:
number = 5 
while number > 0:
    print(number)
    number -= 1

5
4
3
2
1


In [32]:
sum = 0
number = 1
 
while number < 5:
    sum += number
    number +=1
print(sum)

10


In [36]:
number = -1
while number < 1 or number > 10:
    number = int(input('Enter a number from 1 to 10'))

# Collections

## Tuple

In [4]:
tuple = ('Homo Sapiens', 'Canis Familiaris', 'Felis Catus')
tuple[-1]

'Felis Catus'

In [5]:
tuple.index('Felis Catus')

2

In [6]:
for i in tuple:
    print(i)

Homo Sapiens
Canis Familiaris
Felis Catus


## List

In [22]:
list1 = ['Homo Sapiens', 'Canis Familiaris', 'Felis Catus']
list2 = ['Xenopus Leavis' , 'Ailuropoda Melanoleuca'] 

In [11]:
list3 = list1 + list2

In [31]:
result = " ".join(list1 + list2)
result

'Homo Sapiens Canis Familiaris Felis Catus Xenopus Leavis Ailuropoda Melanoleuca'

In [33]:
list2_2 = list2 * 2
list2_2

['Xenopus Leavis',
 'Ailuropoda Melanoleuca',
 'Xenopus Leavis',
 'Ailuropoda Melanoleuca']

In [36]:
list1[0]

'Homo Sapiens'

In [38]:
list1[0:2]

['Homo Sapiens', 'Canis Familiaris']

In [39]:
list1.append('Monkey')
list1

['Homo Sapiens', 'Canis Familiaris', 'Felis Catus', 'Monkey']

In [ ]:
list1.remove('Canis Familiaris')
list1

In [43]:
del(list1)
list1

NameError: name 'list1' is not defined

In [45]:
for i in list2_2:
    print(i)

Xenopus Leavis
Ailuropoda Melanoleuca
Xenopus Leavis
Ailuropoda Melanoleuca


## Dictionary

In [1]:
collect = {'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anpheles darlingi': 14}

In [2]:
collect['Aedes aegypt']

32

In [3]:
collect['Rhodnius montenegrensis'] = 11

In [4]:
collect

{'Aedes aegypt': 32,
 'Aedes albopictus': 22,
 'Anpheles darlingi': 14,
 'Rhodnius montenegrensis': 11}

In [6]:
del(collect)['Aedes albopictus']

In [8]:
collect.items()

dict_items([('Aedes aegypt', 32), ('Anpheles darlingi', 14), ('Rhodnius montenegrensis', 11)])

In [9]:
collect.keys()

dict_keys(['Aedes aegypt', 'Anpheles darlingi', 'Rhodnius montenegrensis'])

In [10]:
collect.values()

dict_values([32, 14, 11])

In [11]:
collect2 = {'Anopheles gambiar': 13, 'Anopheles deaneorum': 14}

In [12]:
collect.update(collect2)

In [13]:
collect

{'Aedes aegypt': 32,
 'Anpheles darlingi': 14,
 'Rhodnius montenegrensis': 11,
 'Anopheles gambiar': 13,
 'Anopheles deaneorum': 14}

In [14]:
collect.items()

dict_items([('Aedes aegypt', 32), ('Anpheles darlingi', 14), ('Rhodnius montenegrensis', 11), ('Anopheles gambiar', 13), ('Anopheles deaneorum', 14)])

In [18]:
for i, ii in collect.items():
    print(f'Species {i}, number of species collected {ii}')

Species Aedes aegypt, number of species collected 32
Species Anpheles darlingi, number of species collected 14
Species Rhodnius montenegrensis, number of species collected 11
Species Anopheles gambiar, number of species collected 13
Species Anopheles deaneorum, number of species collected 14


## Set

In [19]:
biomolecules = ('protein', 'nucleic acid', 'carbohydrate', 'lipid', 'nucleic acid', 'carbohydrate', 'carbohydrate','carbohydrate' )

In [20]:
set(biomolecules)

{'carbohydrate', 'lipid', 'nucleic acid', 'protein'}

In [22]:
c1 = {1,2,3,4,5}
c2 = {3,4,5,6,7,}
c3 = c1.intersection(c2)

In [23]:
c3

{3, 4, 5}

In [24]:
c1.difference(c2)

{1, 2}

In [25]:
c2.difference(c1)

{6, 7}

# Matrix

In [26]:
import numpy as np

In [29]:
matrix = np.array([[2, 3, 1,],
                   [4,5,7]])

In [30]:
matrix

array([[2, 3, 1],
       [4, 5, 7]])

In [32]:
matrix.shape

(2, 3)

In [33]:
matrix[0]

array([2, 3, 1])

In [34]:
matrix[1]

array([4, 5, 7])

In [36]:
matrix[0][2]

1

In [37]:
matrix[1][2]

7

In [43]:
for i in range(matrix.shape[0]):
    print(matrix[i])
    for ii in range(matrix.shape[1]):
        print(matrix[i][ii])

[2 3 1]
2
3
1
[4 5 7]
4
5
7


# Fuction
- Trechos de programa que recebe um determinado nomer e podem ser chamados várias vezes durante a execução
- Principais vantagens: Reutilização de código, modularidade e facilidade de manutenção do sistema.

## Função sem parâmetro e sem retorno 

In [3]:
def mensage():
    print('Function Text')

In [5]:
mensage()

Function Text


## Função com passagem de parâmetro

In [10]:
def mensage(text):
    print(text)

In [11]:
mensage('text 1')
mensage('text 2')
mensage('text 3')

text 1
text 2
text 3


In [15]:
def sum(a, b):
    print(a + b)

In [13]:
sum(3,3)

6

## Função com passagem de parâmetros e retorno

In [16]:
def sum(a, b):
    return a + b    

In [18]:
result = sum(9, 8)
result

17

In [23]:
def calcular_energia_potencial_gravitacional(m, h, g = 10):
    '''
    Calcula a energia pontencial gravitacional
    
    Argumentos:
    m: massa, entrada como uma variável float
    h: altura, entrada como uma variável float
    
    Argumentos opcional:
    g: aceleração gravitacional, com valor default de 10
    '''
    energy = g * m * h
    return energy

In [20]:
calcular_energia_potencial_gravitacional(30, 12)

3600

In [21]:
calcular_energia_potencial_gravitacional(30, 12, 9.8)

3528.0

In [24]:
help(calcular_energia_potencial_gravitacional)

Help on function calcular_energia_potencial_gravitacional in module __main__:

calcular_energia_potencial_gravitacional(m, h, g=10)
    Calcula a energia pontencial gravitacional
    
    Argumentos:
    m: massa, entrada como uma variável float
    h: altura, entrada como uma variável float
    
    Argumentos opcional:
    g: aceleração gravitacional, com valor default de 10

