# Importando Bibliotecas

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

# Regressão Linear Simples

## Base Plano de Saúde

In [4]:
data_plano_saude = pd.read_csv('plano_saude.csv') 

In [5]:
data_plano_saude

idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

## Base Preços das Casas

In [8]:
x_plano_saude = data_plano_saude.iloc[:,0].values
x_plano_saude


array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64)

In [12]:
y_plano_saude = data_plano_saude.iloc[:, 1].values
y_plano_saude

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090],
      dtype=int64)

In [13]:
# coeficiente de correlacao 
np.corrcoef(x_plano_saude, y_plano_saude)   

array([[1.        , 0.93091958],
       [0.93091958, 1.        ]])

In [14]:
x_plano_saude.shape

(10,)

In [ ]:
x_plano_saude.reshape(-1,1)

# Regressão Linear Múltipla